[package]
name = "near-contract-standards"
version.workspace = true
authors = ["Near Inc <hello@near.org>"]
edition = "2021"
license = "MIT OR Apache-2.0"
categories = ["wasm"]
repository = "https://github.com/near/near-sdk-rs"
homepage = "https://near-sdk.io"
documentation = "https://docs.rs/near-contract-standards"
description = """
NEAR smart contracts standard library.
"""

[dependencies]
near-sdk = { path = "../near-sdk", version = "~4.1.1", default-features = false, features = ["legacy", "schemars"] }
near-account-id = {version="1.0.0-alpha.3", features = ["abi", "serde", "borsh", "schemars"]}

[features]
default = ["abi"]
abi = ["near-sdk/abi"]
