[package]
name = "near-sdk-core"
version = "2.0.0"
authors = ["Near Inc <max@nearprotocol.com>"]
edition = "2018"
license = "Apache-2.0"
categories = ["wasm"]
repository = "https://github.com/near/near-sdk-rs"
homepage = "https://github.com/near/near-sdk-rs"
description = """
Core part of the library for writing NEAR smart contracts.
"""

[dependencies]
proc-macro2 = "1.0"
syn = {version = "1.0.14", features = ["full", "fold", "extra-traits", "visit"] }
quote = "1.0"
Inflector = { version = "0.11.4", default-features = false, features = [] }
